### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by XhantorzD** [intrepidcs/libicsneo-examples#1] opened 2019-01-10 13:13 UTC
Can this be built for an arm device? 
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)

```/home/pi/libicsneo/include/icsneo/communication/message/neomessage.h:147:1: error: static assertion failed: neomessage_t may not change size from 72 bytes!
 static_assert(sizeof(neomessage_t) == 72, "neomessage_t may not change size from 72 bytes!");
 ^~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-zero-length-array’
cc1plus: warning: unrecognized command line option ‘-Wno-gnu-anonymous-struct’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
CMakeFiles/icsneocpp.dir/build.make:158: recipe for target 'CMakeFiles/icsneocpp.dir/communication/message/neomessage.cpp.o' failed
make[2]: *** [CMakeFiles/icsneocpp.dir/communication/message/neomessage.cpp.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/icsneocpp.dir/all' failedmake[1]: *** [CMakeFiles/icsneocpp.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by hollinsky-intrepid** [comment] 2019-01-10 21:44
This should be resolved by intrepidcs/libicsneo@34148e8 and was caused by the Pi running in 32-bit mode. The example should work on the Pi with the same compatibility as other Linux-based PCs.

If there are any other issues feel free to let us know!

**Closed as completed by hollinsky-intrepid** 2019-01-10 21:44 UTC
